before_install:
- npm install -g dredd@stable
before_script:
- ls -la
env:
  global:
    secure: iC4kUGzNlYuJ081HkehR7G3vHWjy4el6cY2pfi8dKtExXJjpJoUTCPnAEnLcE5IMbb8yMnKxhsKBCayGNpr4j9JKhqAs5Wik3kG1lrkrDbjmtIVMhisxZvtr+17q1xyuMA59DSbYlWuHTWwxtQ4OMyWebbOrbR5FSu17doOFkgyiMusglHbP98ER32q63HHk/nWZB/03CZ3TxBSrvzUNCRMJ80nUtcoY4pEIJoXQFn9kIml3//TzF8JNVVcmkcIoOhcpjZ4glnXWmmS71r1Zx+YkKEAgE/1BIUu0Xcp/GwGtJP2jMhmtbaavKPvGbaefV/JijjfjRZzy7WgefRgwyaq5chdNJkESoj3B1ma64TudJF35Ou9q710YgWal+Rk87OYTJIsRTKw1tEzzhHtEvUQxAZPYh7vZ8AmDff1JXbRSpkd2Z1V2N1AJptxvLBf9SKKx8nlUBSLMPzrMlCDWKbBnlwmo2h7cvexCABRC5lfTT5tPKzap0SBKL3pKbKx14YypT9FSKBMrMEtNOIfr/w9Mwch8jYnJM6l60Amh0oAf18qP2ye5aQ2M2czA4Sht3DorvSkA1Mbvqt99VJhQ+Uu1ofhWqzB8wLY1ru+VxHEmjiRDS8AU3CXgWWoqqvdowj+54LD0zEY+rtrwktEHYwqQDbiXnjWEIfoJ8NeT398=
